---
- name: Install OMV
  apt:
    name: openmediavault
    state: present
    update_cache: yes
    dpkg_options: "force-confdef,force-confold"
    install_recommends: no
    allow_downgrade: yes
    allow_change_held_packages: yes

- name: OMV Configure Db Admin Populate
  command: omv-confdbadm populate
  changed_when: false

- name: OMV Salt Deploy
  command: omv-salt deploy run systemd-networkd
  changed_when: false
